# build: `docker build -t udpipe/server .`
# run:   `docker run --rm -it -p 8080:8080 udpipe/server`
#
# see also https://github.com/samisalkosuo/udpipe-rest-server-docker
#
FROM ubuntu:18.04

ENV DEFAULT_MODEL english-ewt-ud-2.5-191206.udpipe
ENV MODEL_EN english-ewt-ud-2.5-191206.udpipe
ENV MODEL_DE german-hdt-ud-2.5-191206.udpipe
ENV UDPIPE_PORT 9001


RUN apt-get -q update && \
    apt-get -q install -y curl gcc g++ build-essential git && \
    g++ --version

WORKDIR /
RUN git clone https://github.com/ufal/udpipe.git

# ADD src /udpipe/src
# ADD releases/test_data/${MODEL_FILE_NAME} /models/
# WORKDIR /udpipe/src/rest_server

#RUN cd /udpipe/src && BITS=64 MODE=release make -j4 server
WORKDIR /udpipe/src
RUN BITS=64 MODE=release make -j4 server && \
    mkdir /models && \
    ln -s /udpipe/releases/test_data/${MODEL_FILE_NAME} /models/

EXPOSE ${UDPIPE_PORT}

# udpipe_server [options] port default_model_name MODEL_1 ... MODEL_N
# where each MODEL is represented by three variables (model_name model_file model_description)
CMD /udpipe/src/rest_server/udpipe_server "${UDPIPE_PORT}" "${DEFAULT_MODEL}" "${MODEL_EN}" "/models/${MODEL_EN}" "${MODEL_EN}" "${MODEL_DE}" "/models/${MODEL_DE}" "${MODEL_DE}"
