version: '3.3'
services:

  udpipe1:
    build:
      context: .
      dockerfile: Dockerfile-udpipe-1
    environment:
      - DEFAULT_MODEL=english-ewt-ud-2.5-191206.udpipe
    volumes:
      - "./udpipe-models:/models:ro"
    ports:
      - "9001:9001"

  braud-2017-service:
    build: .
    environment:
      - UDPIPE1_ENDPOINT=http://udpipe1:9001 # connects to the port number IN the container, not the one on the host
    entrypoint: >
      sh -c "python wait_for_it.py -t 20 $${UDPIPE1_ENDPOINT}/process?data &&
             pytest -v"
